/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demos_CQTSapi */

#ifndef _Included_com_demos_CQTSapi
#define _Included_com_demos_CQTSapi
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1JS_SAPI_Init
  (JNIEnv *, jobject, jstring, jstring);


/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_ASRClear
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1ASRClear
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_SetASRRuleValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1SetASRRuleValue
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_TTSClear
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1TTSClear
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_SetTTSRuleValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1SetTTSRuleValue
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Hi_Start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1Hi_1Start
  (JNIEnv *, jobject);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Lo_ASRRule
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1Lo_1ASRRule
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Lo_TTSRule
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1Lo_1TTSRule
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Lo_VoiceRule
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1Lo_1VoiceRule
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Lo_TTSText
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1Lo_1TTSText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_demos_CQTSapi
 * Method:    JS_SAPI_Lo_VoiceFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demos_CQTSapi_JS_1SAPI_1Lo_1VoiceFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
